services:
  - type: web
    plan: free
    name: django-app
    runtime: python
    repo: https://github.com/ZealVira/splitsmart.git
    # buildCommand: './build.sh'
    buildCommand: 'DJANGO_SETTINGS_MODULE=splitsmart.settings.production ./build.sh'

    startCommand: 'python -m gunicorn splitsmart.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER
        value: true


databases:
  - name: django-app-db
    plan: free
    databaseName: django_app
    user: root


