line-length = 100
target-version = "py311"

# ignore common clutter
extend-exclude = [
    "__pycache__",
    ".venv",
    "venv",
    ".git",
    "*/migrations/*",
    "*.egg-info",
    "build",
    "dist",
    ".coverage",
    ".pytest_cache",
]

[lint]
select = ["E", "F", "I", "UP", "DJ", "PL"]
ignore = ["DJ008"]

[format]
quote-style = "double"