# Generated by Django 5.2.4 on 2025-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
